openapi: 3.1.0
info:
  title: Redirector API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/redirects/new:
    parameters: []
    post:
      summary: Creating a new Redirect
      operationId: post-redirect-new
      responses:
        '200':
          description: Redirect created
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirect_from:
                    type: string
                  redirect_to:
                    type: string
              examples: {}
        '400':
          description: Invalid parameters received
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
              examples:
                Missing Parameters:
                  value:
                    error: You are missing the required parameters
                    errorCode: MISSING_PARAMETERS
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
              examples:
                Not Authenticated:
                  value:
                    error: You are not authorized to use this endpoint
                    errorCode: INVALID_AUTH
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
                required:
                  - error
                  - errorCode
              examples:
                Internal Server Error:
                  value:
                    error: The server failed to process your request
                    errorCode: INTERNAL_SERVER_ERROR
      description: Creates a new Redirect
      security:
        - token: []
  '/api/redirects/{redirect_key}':
    parameters:
      - schema:
          type: string
        name: redirect_key
        in: path
        required: true
        description: The key for a redirect (also known as the "redirect_from")
    get:
      summary: Retrieve data for a Redirect
      tags: []
      responses:
        '200':
          description: Redirect Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirect_from:
                    type: string
                  redirect_to:
                    type: string
        '404':
          description: Redirect Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
              examples:
                Redirect Not Found:
                  value:
                    error: The redirect with the provided key was not found
                    errorCode: REDIRECT_NOT_FOUND
      operationId: get-redirect
      description: Allows the caller to retrieve data for an endpoint
      security: []
    patch:
      summary: Update Redirect Destination
      operationId: update-redirect-to
      responses:
        '200':
          description: Redirect Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirect_from:
                    type: string
                  redirect_to:
                    type: string
                required:
                  - redirect_from
                  - redirect_to
              examples:
                Update Successful:
                  value:
                    redirect_from: example
                    redirect_to: 'https://example.com'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
              examples:
                Invalid Parameters:
                  value:
                    error: The parameter you supplied is invalid
                    errorCode: INVALID_PARAMETERS
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
                required:
                  - error
                  - errorCode
              examples:
                Invalid Authentication:
                  value:
                    error: You are not authorized to access this endpoint
                    errorCode: INVALID_AUTH
        '404':
          description: Redirect Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
                required:
                  - error
                  - errorCode
              examples:
                Redirect Not Found:
                  value:
                    error: The supplied Redirection could not be found
                    errorCode: INVALID_PARAMETERS
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
                required:
                  - error
                  - errorCode
              examples:
                Operation Failed:
                  value:
                    error: The server ran failed to process your request
                    errorCode: INTERNAL_SERVER_ERROR
      description: Allows the caller to update the destination for a Redirect
      security:
        - token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                redirect_to:
                  type: string
              required:
                - redirect_to
        description: Allows the caller to update a Redirect's destination
    delete:
      summary: Delete Redirect
      operationId: delete-redirect
      responses:
        '200':
          description: Redirect Removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Operation Successful:
                  value:
                    message: Redirect removed
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
              examples:
                example-1:
                  value:
                    error: You are not authorized to access this endpoint
                    errorCode: INVALID_AUTH
        '404':
          description: Redirect Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
              examples:
                Redirect Not Found:
                  value:
                    error: Failed to find the Redirect to remove
                    errorCode: INVALID_PARAMETERS
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  errorCode:
                    type: string
              examples:
                Operation Failure:
                  value:
                    error: The server failed to process your request
                    errorCode: INTERNAL_SERVER_ERROR
      description: Allow's the caller to delete a Redirect
      security:
        - token: []
components:
  schemas:
    Redirect:
      description: 'Represents a redirect, which will specify the key and the destination'
      type: object
      properties:
        redirect_from:
          type: string
          minLength: 1
        redirect_to:
          type: string
          minLength: 1
      required:
        - redirect_from
        - redirect_to
      x-examples:
        example-1:
          redirect_from: string
          redirect_to: string
  securitySchemes:
    token:
      name: Token
      type: apiKey
      in: header
security:
  - token: []
